language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://anicolas.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "Lij6D0DuNcCQT2zH0Dlqq8ih0Hb9Iworz5Bf1N3hjRs8JEkvYzVDpER3CPsoL0EY0cbxVtjwDcTXjndzzxc0edqQfFK5r88sX+0trFBb8TeYBGkYnXHwUcGsXHoHjbL5ez5NWFkibx7EVB+QTt+TP3WNzG4dPCrRZherx0xRvEh5fKb6xd/6+zKntlWUbJafrfrax6TBbmJND2uxx6U/CZ0XovldNsXospeRP8CLRkGuZo0dtp7pOlX1jfsSDsohT1FEulYPavhXSLpV9jGzSuSqG9AAyHos9XB6Cpos3H3KNdTyueVsQLubeA3p32ovbDaEzJguy6OCUWGpXo+Hq1lniYBIj7OspIEKLU1VTS66pAlFWaMeuujbisvoXQYGp0E/5LQPdRfGcjbx14v1I76AHjh/OSzNooHgRuJjd9XPnE85w1e1k+JbOkYk+BbuljxkjJrbBTUtynpnazoLC3o1WmtPJazbdWmQsRmYATaW3HYeiQXzBlcMLeT9fk05Ag6vtFTPVUCFiRRyF5kzhkpQBEfRGOI3Nn5G6aOTBYZxxbVakKTMQNpQfVMoMJTl1UjUdQfuznuDfmKDyt/cRB1++KD7MPZABQT4ZnNIYvXuFeyWH+7BBmkduEFFN9SgxaOlCeDWDeMgGT9EJ4ssnEc6utzZtpK5yfSB5ywvmto="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
