language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=https://anicolas.pactflow.io
  - PACT_BROKER_BASE_URL=https://test.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "aAVQ1WcGsFIa88ajstW700dfdqzfaj9t37q7+Fgt6GL87hgwYvvsSgNqlaAourP9EXoDAG8IYeSpUeVTj3JEACjsDVtgzb6P08Jrq7BitjDkEu6IcoPNfSdsPhw//WJs1TolOMJlR9utVnraBTroSo9sfaMELFLsrdxR0qnfu0IkVkZ/oVCMHGG5oxFrsdZVuwGg8HtN22iMjT0m1IeZTqXfSyE5FamB94Cuc7Ecfmoh92TI+0mKNahS2HT7VXSKn348MsdHYS1KpZYDjRZOSq4L0xRkul7AWL8rlrRV1UqYDV+N26m6RInD89RqDfDV6Qu4g3BcdnzyqySEunjQxoC4RMQd7UUlnHnM9JhpFM24zuMgS4IZGj4ydlGn6vDT2N5EWf5nWQmnM0+L1+ChlYx8wRA2YaNhVkVUN2HCzChKwN+adWxEpQDJCOALSGdUKaeqwBeFkbKxQQ7UufzepH/RROx/PUoxd1t/GraMGUAdYExgpZ5hJHVu9ouQT0xP9n5fXyZQzfw6LrF7AXKUQnTPG1R0gO5G2ZQ/tAtT8xQsTrdMN5w6FWmoqeASy3sjvLwSQxlxmkoRdhPpHByBKrrZEDBZAFz486MzqXZY9vApKzsyTdmWvgelbJei3b+cXuchtJFH6kF4AFiCCcjbgh3gqrKXOlxfmCVNLl8nhZY="

before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
